### ISSUE TITLE
Queue build based on same changeset

### ISSUE THREAD

**Issue by llykke** [bamminger/vsts-queue-build#1]
It would be really nice for us, if this task could queue a build using the same changeset as the originating build.

We've managed to queue a build using powershell, which look at the changeset on which the initiating build had been queued on, and set that as a property on the build to be queued, in order for it to be run on the same changeset.

The json payload sent to the queue rest API is something along the lines of the below:
```Powershell
 $newBuildArguments = @{ 
  definition=@{
    id=$buildid
    };
  requestedfor = @{
    id=$($originBuildDetails.requestedfor).id
    };
  sourcebranch=$originBuildDetails.sourcebranch;
  sourceversion = $originBuildDetails.SourceVersion;
```
where `$originbuilddetails` is the initiating build. So by setting the sourceversion property in the json payload that we post, we ensure, that the queued build is using the same changeset as the original build.

I've not written extensions for VSTS before in typescript (which I'm assuming you've used?) and hence I don't know how you would extract the sourceversion from the originating build and parse it on to the queued build?

Most likely you would find the sourceversion in the queue-build.ts file, and then pass it on to the constructor of the worker object. You could probably just set the sourceversion as a property right around where you [set the id in the worker.ts file](https://github.com/bamminger/vsts-queue-build/blob/master/src/worker.ts#L58).

All of this of course is in the context of TFVC. I've not taken into account if using Github introduces any weirdness in the above(?).

You might want to make this a drop down menu with the following options:
1. Start on same changeset
1. Start on latest changeset
1. Start on specific changeset (most likely people would want to specify this as a variabel at queuing time of the original build)

I'll try and see if I can get my act together and make this as a pull request, but it might take me some time :-(

**Comment by bamminger** [comment]
This would be definetly a good feature. Your description also makes it easier to implement. Thanks.

A few things that we have to think about:
1. How we gonna handle the changeset within release definitions? There might be no changeset available.
2. How to handle git repositories and queueing two builds with different git repositories.

I will investigate into possible solutions over the next days.

**Comment by bamminger** [comment]
The new version will have the following changes:
1. New field to set the public build variables for each build definition
2. Adding support to set the source of each build. There it will be possible to use the changeset version of the current build by using the variable BUILD_SOURCEVERSION
3. Maybe also the possibility to select a single build definition with a dropdown

**Comment by llykke** [comment]
I assume, that it will use the latest sourceversion, if none is provided?

**Comment by bamminger** [comment]
Correct. That should be the same behaviour like before.

**Comment by cbenoist** [comment]
What is the expected drop time for this release?  The addition of this functionality would be very useful.

**Comment by bamminger** [comment]
Approximately at the end of March.

**Comment by cbenoist** [comment]
is that because of the release process for the marketplace?  How would I go about testing this for you?  Any way I can contribute?

**Comment by bamminger** [comment]
No, the publishing is done almost instantly. Unfortunately I have no time to start the development before next Monday. The remaining days are for testing and extending the documentation. Probably I'm done earlier, but the worst case is end of March. As soon as I have a testable version, I'll come back to your offer.

**Comment by cbenoist** [comment]
Thank you very much for getting back to me on this.  I look forward to the new version.

**Comment by bamminger** [comment]
The new configuration setting can be found here: https://github.com/bamminger/vsts-queue-build/tree/feature/configuration
