### ISSUE TITLE
Case sensitive parsing for build definitions?

### ISSUE THREAD

**Issue by llykke** [bamminger/vsts-queue-build#10]
I've been trying out the newest version of your plugin, and it appears, that it's performing a case sensitive search through all build definitions when looking for the one to queue?

The way I interpret your source, is that you get a list of all build definitions within a team project and try to find one matching the name of the definition to queue.

I would have preferred this selection to be case insensitive.
When I changed the name of the definition to queue from ALL UPPERCASE to Exact Casing, the queue task worked as expected.

You might want to consider the following feature additions:
1) Augment build summary page with information and link to queued build to support direct linking? [This link](http://stackoverflow.com/a/36385410/129352) shows how to write output to build summary page.

Again, Thank you for developing this extension which makes our build proces much more transparent as opposed to custom inline Powershell scripts!

**Comment by bamminger** [comment]
Thanks for your feedback.
The next version will search the definition case insensitive as fallback.
I will investigate into possible output improvements for future releases.

Update:
The new version support case insensitivity.
