### ISSUE TITLE
TFS 2015 Update 3 - task fails with unauthorized error

### ISSUE THREAD

**Issue by Arturas-K** [bamminger/vsts-queue-build#11]
Hi,

This is continuation of issue #7 

I have tried updated version v1.2.2 of this extension.
Also i have verified that "Allow Scripts to Access OAuth Token" option in build definition is enabled.
I have tried "Use Requester User" option on build task itself.
I cant use custom token option since tfs 2015 doesnt have ability to generate personal access tokens, or at least i cant find a way to get it.

But i still get the same unauthorized error.
```
{ [Error: Failed Request: Unauthorized(401) - http://pllwinqatfs001:8080/tfs/ISD/_apis/build] statusCode: 401 }
```
here is full log with debug enabled:
[2_Queue build(s) Fraud and IDUnitTests1.txt](https://github.com/bamminger/vsts-queue-build/files/979187/2_Queue.build.s.Fraud.and.IDUnitTests1.txt)

I suspect that issue is with generated url: 
http://pllwinqatfs001:8080/tfs/ISD/_apis/build
if i copy paste this url to browser i get 404 page not found.

Investigating TFS API documentation i see that url is missing team-project name and resource parts:
https://www.visualstudio.com/en-us/docs/integrate/api/build/definitions
pattern is:
https://{instance}/DefaultCollection/{project}/_apis/build/definitions
Note that project is not optional.

If i amend url to include my project name and definitions resource:
http://pllwinqatfs001:8080/tfs/ISD/Fraud%20and%20ID/_apis/build/definitions
is successful get a response document with all definitions for this team-project.

Could it bet some compatibility issue between TFS 2015/2017/VSTS?

**Comment by mthistle** [comment]
I am seeing the same issue against TFS 2015 Update 3.

**Comment by bamminger** [comment]
Unfortunatelly [there is no way](https://www.visualstudio.com/en-us/docs/integrate/extensions/develop/build-task-schema) to define a minimum TFS Version for an extension. I'm using a microsoft library to access the TFS/VSTS services, which seems to support only the new TFS/VSTS Apis.
At the moment there are no plans to re-implement the API layer. 
Sorry for not being able to support your use-case at the moment.
