### ISSUE TITLE
Multiple Build Definitions

### ISSUE THREAD

**Issue by iliagerman** [bamminger/vsts-queue-build#13]
Hello,
Once I try to trigger more than one build definition I receive the following error: 

Input example: 
Build1
Build2

400: TF20507: The string argument contains a character that is not valid:'u000A'. Correct the argument, and then try the operation again.
 Parameter name: definition.Steps.Step.DisplayName

**Comment by bamminger** [comment]
Which version of TFS are u using or do you have VSTS?
Do you also use build specific configuration settings?

**Comment by iliagerman** [comment]
Tfs 2017, no special build configuration

**Comment by bamminger** [comment]
Unfortunately the used Microsoft library has some problems with an on premise TFS. Hence we can't support that at the moment.
