### ISSUE TITLE
TFS (2017) on premise support?

### ISSUE THREAD

**Issue by japj** [bamminger/vsts-queue-build#17]
Hello,

What would still be needed to be able to support TFS 2017 on premise (the docs explicitly state it is not supported).

According to https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/minagent.md it is possible to specify a minimumAgentVersion to be used for the task. This would allow for targeting a minimum version of TFS by its agent (as mentioned in #11 )

Please also note the latest versions of the used libraries are:
vsts-task-lib: 2.1.0 (2.0.5 is used currently)
vso-node-api: 6.2.8-preview (5.1.2 is used currently, which is the latest stable version)

I can imagine that TFS2015 missed some of the newer Build related APIs and that might be what people have run into before.

**Comment by bamminger** [comment]
So far most of the problems occured on older TFS versions, thats why I added it to the docs.
TFS 2017 should theoretically be compatible with the current release already. Unfortunatelly, I'm not able to test it. Do you have a TFS 2017?
An update to the latest npm packages would be no problem.

**Comment by japj** [comment]
Yes, I have access to TFS2017. Both as a VM (for testing) and our regular
on premises environment. I will try and have a look this week and keep you
updated.

**Comment by llykke** [comment]
We're currently using this extension on a TFS 2017 update 2 on-premise installation and it is working excellent! :-)

**Comment by bamminger** [comment]
I'll update the minimum version of TFS accordingly.
