### ISSUE TITLE
VM (agents) scaling by triggering VM based on agent queue lenght.

### ISSUE THREAD

**Issue by Sebizbir** [bamminger/vsts-queue-build#18]
Is there some factor like Demand (Phase 1) , Variable (Variable tab) on particular build I can set to do below:

When one agent have queue lenght (there are more than one build assigned) of 2, run next agent. Meaning, if one agent is doing a build and some build is awaiting, run second agent.

This setup is for VM scaling where private agents runns.
Right now situation is either one agent (on VM1)  have many build queued or I need to launch few VMs manually.

But I need VM scaling based on VM1 queue, this way next VMs could launch automatically (auto shutdown/deallocate script does closing job).

Maybe some of you know easier way (REST API didnt help as well).

Please advice.

Regards Seb

**Comment by bamminger** [comment]
Sorry, I'm not sure, how exactly your setup looks like. Are you trying to queue builds on one agent an want that agent to process other builds while it is waiting for the queued ones to finish?

**Comment by Sebizbir** [comment]
Hey, can I wrote you priv message somehow?
cheers

**Comment by bamminger** [comment]
On Twitter? https://twitter.com/bamminger

**Comment by Sebizbir** [comment]
please respont my twitts

**Comment by bamminger** [comment]
Which tweets? I have no notifications or private message.

**Comment by Sebizbir** [comment]
Twitter make me crazy - I do not use it - I have account there - already followed you days ago and twitted
