### ISSUE TITLE
When creating original build link, the direction seems opposite?

### ISSUE THREAD

**Issue by llykke** [bamminger/vsts-queue-build#19]
We're using this extension with great succes in our build and release pipelines. One of the new features however, where you create a link between builds, seems to have the opposite direction of what's intended?

We're using TFS 2017 update 2 (on-premise).

If we queue a build, the originating build definition (i.e. the one that's queuing) gets the link with the title/headline 'Original Builds'. The link leads to the build that was queued.

The heading should however most likely have been 'Queued Builds' or something? Then the links would make sense.

Similarly, the queued build does not have any reference back to the original build. I'm not sure how you would do that? Would it be possible to create a link from the queued build, back to the originating build?

We're also using this task in our release pipelines to launch builds as part of a deployment (e.g. Automated UI testing). Here we don't see any links from the release to the queued builds. That would be a nice addition in order to save people only visiting VSTS/TFS once in a while from a lot of bookmarks in their browser. :-)

Thank you for providing a great tool!

**Comment by bamminger** [comment]
Ok, renaming the summary is no problem.

Referencing the build back will probalby only possible if we add an additional task to the queued build, which receives a parameter from the original build.

That there is no summary in case of using it for releases is a known issue. I will investigate into solutions.

**Comment by bamminger** [comment]
The summary has been renamed & looks now a little bit better
![Summary view](https://user-images.githubusercontent.com/22851567/36222137-a1840f1e-11c0-11e8-8122-089c6e986e71.png)

Also the release view contains now the summary
![Release view](https://user-images.githubusercontent.com/22851567/36222264-1fc8dd6e-11c1-11e8-9945-44ebada95ca9.png)
