### ISSUE TITLE
Passing parameters to builds

### ISSUE THREAD

**Issue by cbenoist** [bamminger/vsts-queue-build#2]
It would be very nice if we could also specify things like build numbers or higher level settings that each build spawned could use.

A specific case could be setting up an iOS and Android Xamarin.Forms queue build task and as part build steps prior to this task you can specify the build number that could be used to make sure each version has the same version number used. 

I'm sure there are other examples that we could use to see how valuable having parameters being sent to the build itself.

**Comment by bamminger** [comment]
I'm not sure whether this is possible, but I'll check the VSTS API.

**Comment by bamminger** [comment]
Unfortunatelly [queueing the build](https://www.visualstudio.com/en-us/docs/integrate/api/build/builds#queue-a-build) provides no possibilities to pass those settings per build.

A possible solution would be to update the build definition on each build queued and modify/update the definition. Afterwards we could change it back to the original value.
Would that be an acceptable way to go for you? @cbenoist ?

**Comment by chgian** [comment]
I have a very strange behaviour. I have two builds that copy files. One takes no parameters, the second takes the target machine as parameter. By using Queue Build, I can execute the build without parameter successfully. When I try to execute the build which requires parameters, task never ends and files are not copied. But, when I cancel the task, then files appear in target machine. Any ideas?

**Comment by bamminger** [comment]
Can you please open a new issue for your request and share more details about your configuration and your environment.
I'm using it for a comparable situation which works so far.
