### ISSUE TITLE
Agentless phase support

### ISSUE THREAD

**Issue by kdubau** [bamminger/vsts-queue-build#20]
VSTS now has [Agentless phases](https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/phases#server-phase), but this task is only available on Agent phases. I'm wondering if it can support Agentless as well?

**Comment by bamminger** [comment]
I don't think so. The currently available Agentless tasks don't have any custom code or library they need.
They defined the whole task within the task.json
Unfortunatelly I haven't found any documentation for details.

https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/InvokeRestApi
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ManualIntervention
