### ISSUE TITLE
Queue build across TFS projects

### ISSUE THREAD

**Issue by alexJyerkes** [bamminger/vsts-queue-build#21]
Any way of queuing a new build across TFS projects?

**Comment by bamminger** [comment]
Yes, that would be possible. Should that be added to the next version?

**Comment by alexJyerkes** [comment]
Yeah, that would be great!

**Comment by bamminger** [comment]
It's now possible to define the Team project per task/build
See [Documentation](https://github.com/bamminger/vsts-queue-build/blob/master/doc/team-project.md) for further details
