### ISSUE TITLE
Adding build link to the task logs

### ISSUE THREAD

**Issue by ameyagholkar** [bamminger/vsts-queue-build#22]
## Summary
We're using this extension to queue new builds from a VSTS release. Firstly, kudos for this extension 🎉. It was exactly what we needed.

### Suggestion
One point we did see is that the logs that are printed out have the information about the build name et all -- but doesn't have the link to the build's overview or definition. Is that something that could be easily added?

**Comment by bamminger** [comment]
Thank you.
That there is no summary information within a release process is already a know issue #19.

A fix will be available in the next release

**Comment by ameyagholkar** [comment]
Awesome thank you @bamminger 👍

**Comment by bamminger** [comment]
The link to the queued build is now also shown in the log output.
![Log output](https://user-images.githubusercontent.com/22851567/36221965-16f0d486-11c0-11e8-985c-312353081a97.png)
Is that okay?

Also the summary of the build/release has been improved, which contains also clickable links
![Summary](https://user-images.githubusercontent.com/22851567/36222069-6ab3d91a-11c0-11e8-9a46-ce59e72d342c.png)
