### ISSUE TITLE
When we queue the same build lets say different variable. Is it possible to display the Build definition that is queued with the variable value somewhere in the build page? 

### ISSUE THREAD

**Issue by sheshu19** [bamminger/vsts-queue-build#23]
For example I have a build definition "Nightly" and lets say I have a variable "productName" which is passed during queue time. Is there a way to display this variable value, for which the build was queued against in the build page?

**Comment by bamminger** [comment]
Yes, we could improve the build output. How do you want to define the variables that should be displayed or should we display all of them? Another possibility would be to add a display template to define it per build/task.
Any suggestion on how to display it within the current view?

**Comment by sheshu19** [comment]
if we can display some information about the build variable in the build page itself without going into the build logs that will be great..

Ex : In the build page something like

DefinitionName ||  QueueName ||  Source || Product (in my case this is a variable passed to the build) 

Not sure if it is possible to customize the build summary page. 

For now : i have a PS script that displays the variables as the first step in the build. But for that we have to open the build logs and see the variables that are passed.

**Comment by bamminger** [comment]
Is the following image what you would expect?
![task_summary](https://user-images.githubusercontent.com/22851567/37180162-574e712c-2328-11e8-8354-c2ab8fbc5dd9.png)

If it is, I would suggest to make it configurable and you can display any additional details for a queue build. In a template you can specify which on how your variables + predefined variables should be displayed.

**Comment by sheshu19** [comment]
Hello, Thanks for looking into this.. Yes this is something I'm looking for. Could you let me know how to configure the template for achieving this? (or if there are any links I can go through).

I was initially looking for the variable to display under the build section. in the red rectangle in the screenshot. If I can get to know my variable value without going into the build logs that works perfect for me. 

![buildid](https://user-images.githubusercontent.com/20591292/37190323-0d36a874-2351-11e8-8654-5177d61a364d.PNG)

**Comment by bamminger** [comment]
Ohhh, I thought you meant the build specific page, not the build definitiln overview page.
Sorry, I don't think it's possible to change this page.
