### ISSUE TITLE
Wildcards für MultiBuilds

### ISSUE THREAD

**Issue by gclpixel** [bamminger/vsts-queue-build#25]
Hi,
it is possible to use wild cards for searching build definitions?
I want to queue all build in a specified subfolder.

Thanks

**Comment by bamminger** [comment]
Not yet, but we can add this as a new feature.
Would you like to use the same configuration for all builds or different configurations per builds/for some builds?

**Comment by gclpixel** [comment]
Hi,
I would like to write "\SubFolder\*" for queuing all build definitions that are located directly under this folder, all of them with the same configuration. It is like "\SubFolder\Build 01" and "\SubFolder\Build 02" and so on. 
My problem is that these build definitions can change overtime. Sometimes new definitions are added to the subfolder or are removed.

**Comment by bamminger** [comment]
Sorry for the delay. The new version supports [wildcards](https://github.com/bamminger/vsts-queue-build/blob/master/doc/build-definition.md).
