### ISSUE TITLE
Can i choose which build agent should the new build go for? 

### ISSUE THREAD

**Issue by sheshu19** [bamminger/vsts-queue-build#26]
when i'm using the Queue builds task to queue a build definition Can i specify a parameter at run time to queue the build in a particular build agent?

Basically i want to pass the Build Agent Demand for the build at the run time. is this possible?

something like Agent.computerName==>Test1

**Comment by bamminger** [comment]
You can pass a demand via the configuration setting to your build.
Have a look at the docs [here](https://github.com/bamminger/vsts-queue-build/blob/master/doc/configuration.md).
