### ISSUE TITLE
Unfortunately this task doesn't respect agent.proxyurl and agent.proxypassword

### ISSUE THREAD

**Issue by gereon77** [bamminger/vsts-queue-build#28]
Unfortunately this task doesn't work if your agent is behind a proxy. It always responds with connection refused. If you could manage to make this work behind a proxy it would be great.

Thanks in advance

**Comment by bamminger** [comment]
The used VSTS node lib supports proxy [settings](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/proxy.md). 
How should the configuration work?

**Comment by gereon77** [comment]
To be honest, I don't know exactly how to make it work. On my own tries $env:agent_proxypassword is always null whereas $env:agent_proxyusername and proxyurl is available.

But maybe this helps to solve the issue. I also use the "Retain indefinetly" extension from Mario and this works perfect behind the proxy. He doesn't do any special proxy handling but he uses SYSTEMVSSCONNECTION. Maybe that does the trick?

https://github.com/mmajcica/retain-release/blob/master/retain-release/task.ts

Thanks for your response!

Best regards

**Comment by bamminger** [comment]
Ok, it seems like a newer version of the VSTS lib could solve the issue.
I'm using the same way of getting the VSTS connection as the referenced release task.
https://github.com/bamminger/vsts-queue-build/blob/master/src/task/configuration/environment.configuration.ts#L109
https://github.com/bamminger/vsts-queue-build/blob/master/src/task/vsts-api.ts#L23

**Comment by gereon77** [comment]
Yea, probably.

The new version of the node api module is taking care of agent proxy settings without the need to pass those as an option parameter. For the older versions this was not the case.

https://github.com/Microsoft/vsts-node-api/blob/1dc7a4af55e588ed7143b7bb563fb92ba385f291/api/WebApi.ts#L89

When will you provide a new release?

**Comment by bamminger** [comment]
I have to test and then publish the new package.
Approx. at the end of this week.

**Comment by bamminger** [comment]
Extension was updated.
