### ISSUE TITLE
TLS issue

### ISSUE THREAD

**Issue by dnwlf** [bamminger/vsts-queue-build#29]
I'm using the Queue Builds task on a TFS server with a domain-signed cert, and recently started getting the following error running a build:

```
==============================================================================
Task         : Queue Build(s)
Description  : Start new build(s) in your Team Project
Version      : 1.7.0
Author       : jb
Help         : 
==============================================================================
{ Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
Queued builds linked to build result
Queue build(s) failed
```

Unfortunately, I can't pin down when it stopped working, but it last worked on 5/23, and we haven't made any build definition, TFS, or certificate changes in that time.

**Comment by bamminger** [comment]
Thanks for your issue. Could be a problem with the underlying VSTS lib which was updated recently #28

**Comment by bamminger** [comment]
Which TFS Version do you have and do you use a proxy?
https://github.com/Microsoft/vsts-agent/issues/1341

**Comment by dnwlf** [comment]
Thanks for your quick response; I'm on TFS 2017.3.1, and am not using a proxy.

**Comment by dnwlf** [comment]
Just realized that you were looking for the VSTS agent version. The version it failed on is 2.122.1. I can try a newer version, but we've run into some compatibility issues with TFS 2017.3.1 and some of the newer VSTS Agent versions (last tested 2.130). I will test with the latest agent version though and post the results here.

**Comment by dnwlf** [comment]
Same error using latest stable agent version, 2.134.2

**Comment by bamminger** [comment]
Thanks for the information. I will look into it.

**Comment by bamminger** [comment]
Could you try to change the node config with the following command and tell me if this helps?
`npm config set strict-ssl false`

The cause for the issue seems to be the missing root CA for your certificate.

**Comment by dnwlf** [comment]
That does fix the issue, so I consider this issue closed. The problem is on my end, due to the inability to run TFS with a third-party CA. Thanks!

**Comment by toltec7** [comment]
Hi, I just started experiening the same issue with the "Error: unable to get local issuer certificate", and wondered if you could expand on where to run the npm command you highlighted on Jun 29

I am using an on premise TFS Version 16.131.28002.2
agent version 2.136.1
and your lates version 1.7

Last successful run was 5th Oct, then it started throwing this error?
cheers
