### ISSUE TITLE
Custom build queue based on user-defined group variables

### ISSUE THREAD

**Issue by vijak118** [bamminger/vsts-queue-build#30]
Hi,

We've a situation where we need to queue the build based on a user defined group variable value at run time while deploying the release.

May I know if there's a way we can achieve this with the queue build task?

**Comment by bamminger** [comment]
The build name is defined in that variable?
If thats the case, you should be able to use the normal variable syntax (same for the [Configuration](https://github.com/bamminger/vsts-queue-build/blob/master/doc/configuration.md))

**Comment by bamminger** [comment]
Question answered?
