### ISSUE TITLE
Use wildcards to queue builds recursively

### ISSUE THREAD

**Issue by Stumat** [bamminger/vsts-queue-build#31]
Hi,
I am trying to use the wildcard feature in the build definition name field to queue builds in the current folder and subdirectories using the "**" pattern in a path : \Root\Folder1\**\* but it doesn't look like it's working.
Is there another way I can achieve this with this task ?

**Comment by bamminger** [comment]
Sorry ** is currently not supported but we could add it as a new feature. 
The * syntax is currently only capable of looking for all builds in one folder.

**Comment by Stumat** [comment]
Thank you, waiting for the feature then !
