### ISSUE TITLE
How to queue a build providing a specific pool agent?

### ISSUE THREAD

**Issue by gugavaro** [bamminger/vsts-queue-build#34]
I am trying to queue a build, but I would like the build to run In a different agent pool.
I tried to provide the AgentPoolQueue property among the other properties, but it does not see to work. 
Do you have an example of how we could do that?
In fact would be kind a good experience if we have a separate field for that where we can just put the agentpoolname and the task figure how to populate the field internally.

**Comment by bamminger** [comment]
One option would be to use demands.
Have you tried setting the queue property and in there the name (or id)?

**Comment by gugavaro** [comment]
thank you, I will give it a try

**Comment by gugavaro** [comment]
I was able to queue it by using the queueid, it is not ideal for my scenario, but since it works I take it :)

"queue" : {  "id": "queueId" },

you can close the issue.

thanks,
Gustavo.
