### ISSUE TITLE
Difference between succeeded and partially succeeded builds

### ISSUE THREAD

**Issue by Stumat** [bamminger/vsts-queue-build#36]
Hi,
Do you think that it could be possible to show the difference between succeeded builds and partially succeeded builds on the summary screen ?
![image](https://user-images.githubusercontent.com/16701036/47430926-05ae1e80-d79b-11e8-9bce-2d87f94567e3.png)
Thanks !

**Comment by bamminger** [comment]
Sure, sounds like a good idea.

**Comment by bamminger** [comment]
Available in v2 of the task
![image](https://user-images.githubusercontent.com/22851567/78451134-e56ada80-7683-11ea-84ad-58d4c60210c2.png)
