### ISSUE TITLE
Changing "Requested by"

### ISSUE THREAD

**Issue by steenstn** [bamminger/vsts-queue-build#5]
Would it be possible to change the "Requested by" to have the requester of the queueing build as the requester on the queued build? At the moment the queued build will be "Requested by" Project Collection Build Service.

So starting build A which in turn queues build B gives the following result:
```
Build: A - Requested by steenstn
Build: B - Requested by Project Collection Build Service
```
And I would like to have
```
Build: A - Requested by steenstn
Build: B - Requested by steenstn
```

So that the person whose commit breaks the chain can be easily identified.

**Comment by bamminger** [comment]
The Rest API of VSTS does not support that at the moment, but I will investigate into this for a possible solution.

The VSTS possibilities: https://www.visualstudio.com/en-us/docs/integrate/api/build/builds#queue-a-build

**Comment by bamminger** [comment]
You can specify the requestor via the parameters field. Unfortunately it's not possible to specify the parameters without the default or build specific setting:
```json
{
    "default": {
        "sourceBranch": "$(Build.SourceBranch)",
        "sourceVersion": "$(Build.SourceVersion)",
        "requestedFor": {
            "id": "$(Build.RequestedForId)"
        },
        "parameters": {
            "system.debug": "$(system.debug)"
        }
    }
}
```

I will create a new version where this setting can also be controled via checkbox.

**Comment by steenstn** [comment]
Works like a charm, thank you!
