### ISSUE TITLE
queue-build task failing with unauthorized error

### ISSUE THREAD

**Issue by Arturas-K** [bamminger/vsts-queue-build#7]
Hi,

I'm trying out your extensions, and it looks like what i need.
But i'm having issues during execution.
Me set up is TFS 2015 Update 3 on premise installation.
I have configured two agents to run in interactive mode on my workstation.
When i execute the build i get following output:
```
Set workingFolder to default: C:\agent\tasks\queue-build\1.1.0\task
SYSTEMVSSCONNECTION exists true
TFS uri: http://tfsserver:8080/tfs/ISD/
Team project: TestProject
Build configuration null
Build configuration parsed: Input:  null,
Global: null,
Build specific:  null
Build(s) to start (plain) UnitTests1
{ [Error: Failed Request: Unauthorized(401) - http://tfsserver:8080/tfs/ISD/_apis/build] statusCode: 401 }
Queue build(s) faild
```
Build agent account definitely has permissions to TFS as it is running under my windows account in interactive mode.

Do you have any advice how to trouble shoot this?
Thanks

**Comment by bamminger** [comment]
Unfortunatelly the task is not able to get the authentication token of the build agent.
Do you have a setting called "Allow Scripts to Access OAuth Token" or something comparable in your on premise TFS?

**Comment by bamminger** [comment]
The new version will support a custom input field for the authentication token. You could use that field to provide a custom access token to queue your builds successfully.

@Arturas-K The new version is published. Please try it again with that version.

**Comment by Arturas-K** [comment]
@bamminger thanks for info.
Looking forward to new versions.
In the mean time i'll investigate this "Allow Scripts to Access OAuth Token" setting in TFS.

**Comment by bamminger** [comment]
If you need further help, don't hesitate to open another github issue.
